[package]
name = "deno_std_wasm_casemap"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
icu_casemap = "2.0.0"
icu_locale_core = "2.0.0"
wasm-bindgen = "=0.2.100"

[profile.release]
lto = true
codegen-units = 1
